server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  h2:
    console:
      enabled: true
      path: /h2-console

vanilla:
  logging:
    mode: console
    path: ${vanilla.home}/logs
    file:
      name: api-server
      extention: .log