server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

log:
  path:
  file-name: vanilla-scheduler
  file-extention: log
  level: debug
  max-history: 30
  max-size: 300MB
  show-sql: true
  