spring:
  profiles:
    active: local

log:
  path:
  file-name: vanilla-scheduler
  file-extention: log
  level: debug
  max-history: 30
  max-size: 300MB
  show-sql: true

datasource:
  host: localhost
  port: 3306
  username: root
  password: Dydgus070^

ebest:
  resources: 'C:\\eBEST\\xingAPI\\Res'
  connect:
    szServerIP: 'hts.ebestsec.co.kr'
    nServerPort: 20001
    connectTimeOut: 5000
    requestReadTimeOut: 10000
